{
  config,
  lib,
  agentSources ? { },
  ...
}:
let
  cfg = config.development.agents;
  ponytail = agentSources.ponytail or null;
  anyAgentEnabled =
    config.development.claude.enable
    || config.development.cursor.enable
    || config.development.codex.enable
    || config.development.opencode.enable;
  rtkEnabled = builtins.elem "rtk" cfg.packages;
  opencodeSkills = lib.filterAttrs (
    _: source: ponytail == null || !lib.hasPrefix "${ponytail}/skills/" (toString source)
  ) cfg.skills;
  codexSkills = lib.removeAttrs cfg.skills [ "agent-browser" ];
in
{
  options.development = {
    agents = {
      packages = lib.mkOption {
        type = lib.types.listOf (
          lib.types.enum [
            "nodejs"
            "agent-browser"
            "opencode-desktop"
            "rtk"
          ]
        );
        default = [
          "nodejs"
          "agent-browser"
          "opencode-desktop"
          "rtk"
        ];
        description = "Packages installed for enabled AI agents. opencode-desktop is installed only when development.opencode.enable is also enabled. rtk token-compacts CLI output for the enabled agents via activation-time `rtk init`. Removing agent-browser also removes its default skill and instruction.";
        example = [ "agent-browser" ];
      };

      instructions = lib.mkOption {
        type = lib.types.lines;
        default = ''
          # Agent Instructions

          - Always make the smallest idiomatic change that cleanly solves the task while remaining DRY, KISS and maintainable.
          - Follow the project's existing style, structure, and conventions.
          - Never add AI attribution to commit messages (no "Co-authored-by", "Generated by", etc.).
          - Before committing, pushing, or opening a PR, show the proposed changes and commit message and always wait for approval.
          - When writing German, use normal umlauts instead of replacements such as `oe`.
          - Avoid unnecessary complexity, over-engineering, and premature optimization.
          - Remove code made obsolete by your changes.
          - If a task requires an unavailable package, use `nix shell` to run it.
        '';
        description = "Base instructions shared by Claude Code, Codex, Cursor, and OpenCode. Setting this option replaces the default base instructions.";
        example = ''
          # Project instructions

          - Run the test suite before committing.
        '';
      };

      agentBrowserInstructions = lib.mkOption {
        type = lib.types.lines;
        default = lib.optionalString (builtins.elem "agent-browser" cfg.packages) ''
          - For browser automation and web testing, prefer a capable harness-native browser tool. Otherwise use `agent-browser` and keep `agent-browser dashboard start` running so the session stays visible at http://localhost:4848.
        '';
        defaultText = lib.literalExpression ''optionalString (elem "agent-browser" development.agents.packages) "<agent-browser instructions>"'';
        description = "Browser automation instructions appended to the agents that keep the agent-browser skill. Empty unless agent-browser is selected in development.agents.packages. Codex never receives them because its harness provides its own browser tooling.";
      };
    };

    claude.enable = lib.mkEnableOption "Claude Code with shared instructions and skills, programs.mcp.servers integration, and the cc shell alias";
    codex.enable = lib.mkEnableOption "Codex with shared instructions and skills, programs.mcp.servers integration, and the cx shell alias";
    cursor.enable = lib.mkEnableOption "Cursor CLI with shared AGENTS.md instructions, .agents/skills links, the Ponytail rule, and the ccli shell alias";
    opencode.enable = lib.mkEnableOption "OpenCode with shared instructions and skills, programs.mcp.servers integration, the Ponytail plugin, and the opc shell alias";
  };

  config.programs = {
    mcp.enable = anyAgentEnabled;

    claude-code = lib.mkIf config.development.claude.enable {
      enable = true;
      enableMcpIntegration = true;
      context =
        cfg.instructions + cfg.agentBrowserInstructions + lib.optionalString rtkEnabled "\n@RTK.md";
      skills = cfg.skills;
    };

    codex = lib.mkIf config.development.codex.enable {
      enable = true;
      enableMcpIntegration = true;
      context = cfg.instructions + lib.optionalString rtkEnabled "\n@RTK.md";
      skills = codexSkills;
    };

    opencode = lib.mkIf config.development.opencode.enable {
      enable = true;
      enableMcpIntegration = true;
      context = cfg.instructions + cfg.agentBrowserInstructions;
      skills = opencodeSkills;
      settings.plugin = lib.optional (ponytail != null) "${ponytail}/.opencode/plugins/ponytail.mjs";
    };

    zsh.shellAliases = lib.mkMerge [

      (lib.mkIf config.development.claude.enable { cc = "claude"; })
      (lib.mkIf config.development.cursor.enable { ccli = "cursor-agent"; })
      (lib.mkIf config.development.codex.enable { cx = "codex"; })
      (lib.mkIf config.development.opencode.enable { opc = "opencode"; })
    ];
  };

  config.home.sessionVariables = lib.mkIf config.development.opencode.enable {
    OPENCODE_DISABLE_EXTERNAL_SKILLS = "1";
  };
}
