{
  pkgs,
  lib,
  config,
  agentSources ? { },
  ...
}:
let
  cfg = config.development.agents;
  ponytail = agentSources.ponytail or null;
  mattPocockSkills = agentSources.matt-pocock-skills or null;
  cursorPlugins = agentSources.cursor-plugins or null;
  hasSource = source: source != null;
  hasPackage = builtins.elem;

  anyAgentEnabled =
    config.development.claude.enable
    || config.development.cursor.enable
    || config.development.codex.enable
    || config.development.opencode.enable;

  shouldInstallPackage =
    name: if name == "opencode-desktop" then config.development.opencode.enable else anyAgentEnabled;
  enabledPackages = lib.filter shouldInstallPackage cfg.packages;

  agentInstructions = ''
    # Agent Instructions

    - Always make the smallest idiomatic change that cleanly solves the task while remaining DRY, KISS and maintainable.
    - Follow the project’s existing style, structure, and conventions.
    ${lib.optionalString (hasPackage "agent-browser" cfg.packages) "- For browser automation and web testing, prefer a capable harness-native browser tool; otherwise use `agent-browser` and keep `agent-browser dashboard start` running so the session stays visible at http://localhost:4848."}
    - Never add AI attribution to commit messages (no "Co-authored-by", "Generated by", etc.).
    - Before committing, pushing, or opening a PR, show the proposed changes and commit message, then wait for approval.
    - When writing german always write normal umlauts not e.g. oe.
    - Avoid unecessary complexity, over-engineering, and premature optimization. Favor simplicity, clarity, and maintainability.
    - Avoid unecessary code, after making changes check if old parts can be cleaned up.
  '';
  opencodeReviewer = ''
    ---
    description: Two-axis code reviewer combining Matt Pocock's code-review skill with ponytail's over-engineering lens. Use when asked to review a branch, PR, or diff since a fixed point.
    mode: primary
    model: openai/gpt-5.6-luna
    variant: high
    permission:
      "*": allow
      edit: deny
    ---
  ''
  + lib.optionalString (hasSource mattPocockSkills) (
    builtins.readFile "${mattPocockSkills}/skills/engineering/code-review/SKILL.md"
  )
  + lib.optionalString (hasSource ponytail) (
    builtins.readFile "${ponytail}/skills/ponytail/SKILL.md"
  );
  ponytailSkills = [
    "ponytail"
    "ponytail-review"
    "ponytail-audit"
    "ponytail-debt"
    "ponytail-gain"
    "ponytail-help"
  ];
  collectSkills =
    prefix: root:
    let
      entries = builtins.readDir root;
      dirs = builtins.filter (n: entries.${n} == "directory") (builtins.attrNames entries);
      name = d: if prefix == "" then d else "${prefix}/${d}";
      here = builtins.filter (d: builtins.pathExists "${root}/${d}/SKILL.md") dirs;
      nested = builtins.concatMap (d: collectSkills (name d) "${root}/${d}") dirs;
    in
    (map name here) ++ nested;
  mattPocockSkillNames = lib.optionals (hasSource mattPocockSkills) (
    collectSkills "" "${mattPocockSkills}/skills"
  );
  agentSkills =
    lib.optionalAttrs (hasSource ponytail) (
      lib.listToAttrs (map (name: lib.nameValuePair name "${ponytail}/skills/${name}") ponytailSkills)
    )
    // lib.optionalAttrs (hasSource mattPocockSkills) (
      lib.listToAttrs (
        map (
          name: lib.nameValuePair "matt-pocock/${name}" "${mattPocockSkills}/skills/${name}"
        ) mattPocockSkillNames
      )
    )
    // lib.optionalAttrs (hasPackage "agent-browser" cfg.packages) {
      agent-browser = "${pkgs.agent-browser}/skills/agent-browser";
    }
    // lib.optionalAttrs (hasSource cursorPlugins) {
      unslop = "${cursorPlugins}/pstack/skills/unslop";
    };
  agentSkillLinks = lib.mapAttrs' (
    name: source: lib.nameValuePair ".agents/skills/${name}" { inherit source; }
  ) config.development.agents.skills;
  packageByName = {
    inherit (pkgs) nodejs agent-browser opencode-desktop;
  };
in
{
  options.development = {
    agents = {
      packages = lib.mkOption {
        type = lib.types.listOf (
          lib.types.enum [
            "nodejs"
            "agent-browser"
            "opencode-desktop"
          ]
        );
        default = [
          "nodejs"
          "agent-browser"
          "opencode-desktop"
        ];
        description = "Packages installed for enabled AI agents. opencode-desktop is installed only when development.opencode.enable is also enabled. Removing agent-browser also removes its default skill and instruction.";
        example = [
          "agent-browser"
        ];
      };

      instructions = lib.mkOption {
        type = lib.types.lines;
        default = agentInstructions;
        description = "Complete instructions shared by Claude Code, Codex, Cursor, and OpenCode. Setting this option replaces all default instructions.";
        example = ''
          # Project instructions

          - Run the test suite before committing.
        '';
      };

      skills = lib.mkOption {
        type = lib.types.attrsOf lib.types.path;
        default = agentSkills;
        defaultText = lib.literalExpression ''
          {
            ponytail = "<ponytail>/skills/ponytail";
            ponytail-review = "<ponytail>/skills/ponytail-review";
            ponytail-audit = "<ponytail>/skills/ponytail-audit";
            ponytail-debt = "<ponytail>/skills/ponytail-debt";
            ponytail-gain = "<ponytail>/skills/ponytail-gain";
            ponytail-help = "<ponytail>/skills/ponytail-help";
            "matt-pocock/<category>/<skill>" = "<matt-pocock-skills>/skills/<category>/<skill>";
            agent-browser = "<agent-browser>/skills/agent-browser";
            unslop = "<cursor-plugins>/pstack/skills/unslop";
          }
        '';
        description = "Complete skill set shared by Claude Code, Codex, Cursor, and OpenCode. The default contains ponytail, ponytail-review, ponytail-audit, ponytail-debt, ponytail-gain, ponytail-help, every Matt Pocock skill as matt-pocock/<category>/<skill>, agent-browser when selected in development.agents.packages, and unslop. Setting this option replaces all default skills.";
        example = lib.literalExpression ''
          {
            project = ./skills/project;
          }
        '';
      };
    };

    claude.enable = lib.mkEnableOption "Claude Code with shared instructions and skills, programs.mcp.servers integration, and the cc shell alias";
    codex.enable = lib.mkEnableOption "Codex with shared instructions and skills, programs.mcp.servers integration, and the cx shell alias";
    cursor.enable = lib.mkEnableOption "Cursor CLI with shared AGENTS.md instructions, .agents/skills links, the Ponytail rule, and the ccli shell alias";
    opencode.enable = lib.mkEnableOption "OpenCode with shared instructions and skills, programs.mcp.servers integration, the Ponytail plugin, and the opc shell alias";
  };

  config = {
    home.packages =
      map (name: packageByName.${name}) enabledPackages
      ++ lib.optionals config.development.cursor.enable [ pkgs.cursor-cli ];

    programs = {
      mcp.enable = anyAgentEnabled;

      claude-code = lib.mkIf config.development.claude.enable {
        enable = true;
        enableMcpIntegration = true;
        context = config.development.agents.instructions;
        skills = config.development.agents.skills;
      };

      codex = lib.mkIf config.development.codex.enable {
        enable = true;
        enableMcpIntegration = true;
        context = config.development.agents.instructions;
        skills = config.development.agents.skills;
      };

      opencode = lib.mkIf config.development.opencode.enable {
        enable = true;
        enableMcpIntegration = true;
        context = config.development.agents.instructions;
        skills = config.development.agents.skills;
        settings.plugin = lib.optional (hasSource ponytail) "${ponytail}/.opencode/plugins/ponytail.mjs";
      };

      zsh.shellAliases = lib.mkMerge [
        (lib.mkIf config.development.claude.enable { cc = "claude"; })
        (lib.mkIf config.development.cursor.enable { ccli = "cursor-agent"; })
        (lib.mkIf config.development.codex.enable { cx = "codex"; })
        (lib.mkIf config.development.opencode.enable { opc = "opencode"; })
      ];
    };

    home.file = lib.mkIf config.development.cursor.enable (
      {
        ".agents/AGENTS.md".text = config.development.agents.instructions;
      }
      // lib.optionalAttrs (hasSource ponytail) {
        ".agents/rules/ponytail.md".source = "${ponytail}/.agents/rules/ponytail.md";
      }
      // agentSkillLinks
    );
  };
}
