{ lib, ... }:
{
  # Replace with hardware generated by:
  # nixos-generate-config --show-hardware-config > private/hosts/<host>/hardware-configuration.nix
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
}
